version: '3.7'

services:
  postgres:
    image: postgres:10-alpine    
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust 
  web:
    build: .
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && foreman start -f Procfile.dev"
    volumes:
      - .:/bookshelf
      - ./bundle_cache:/bundle:rw,delegated
      - ./node_modules:/bookshelf/node_modules:rw,delegated
    ports:
      - "80:3000"
      - "3035:3035"
    depends_on:
      - postgres     
    env_file:
     - .env
  